name: Documentation
on:
    push:
        branches-ignore:
            - "releases/**"
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "macos.yml"
            - "windows.yml"
            - "ubuntu.yml"
    pull_request:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "macos.yml"
            - "windows.yml"
            - "ubuntu.yml"
jobs:
    doxygen:
        name: Doxygen
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y doxygen
            - name: Generate documentation
              run: |
                  cmake -B build -DDOXYGEN_WARN_AS_ERROR=NO
                  cmake --build build --target bvlib_documentation
    