name: Main
on:
  push:
    branches-ignore:
      - 'releases/**'
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
jobs:
  doxygen:
    name: Doxygen
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Generate documentation
        run: |
          cmake -B build -DDOXYGEN_WARN_AS_ERROR=NO
          cmake --build build --target bvlib_documentation
  test:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build -DBVLIB_BUILD_TESTS=ON -DWARNINGS_AS_ERRORS=ON ${{ matrix.extra-cmake-arguments }}
          cmake --build build --parallel 2
      - name: Test
        run: ctest -C Debug --test-dir build --no-tests=error --verbose